[package]
name = "termtris"
version = "0.1.0"
authors = ["Hannes <7892467+hannes-dev@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
tui = "0.8"
termion = "1.5.5"